### ISSUE TITLE
tbm aceitei o desafio

### ISSUE THREAD

**Issue by SayronBR** [MilenaCarecho/30diasDeCSS#19]
nome: Eduardo
 perfil no GitHub: https://github.com/SayronBR
perfil no LinkedIn:https://www.linkedin.com/in/eduardo-costa-da-silva-895544163/

**Comment by MilenaCarecho** [comment]
Opa
Tudo bem ?
Comenta suas redes nesse issue [aqui](https://github.com/MilenaCarecho/30diasDeCSS/issues/1) para que as outras pessoas do projeto possa te seguir e você seguir elas 😊
