### ISSUE TITLE
Desafio 30 dias de CSS

### ISSUE THREAD

**Issue by R4YC0NLima** [MilenaCarecho/30diasDeCSS#21]
Olá! Meu nome é Raycon
Seu perfil no GitHub: @R4YC0NLima
Seu perfil no Twitter: @RayconBatista
Seu perfil no LinkedIn: raycon-lima-batista-50baa797

**Comment by MilenaCarecho** [comment]
Opa
Tudo bem ?
Comenta suas redes nesse issue [aqui](https://github.com/MilenaCarecho/30diasDeCSS/issues/1) para que as outras pessoas do projeto possa te seguir e você seguir elas 😊
