### ISSUE TITLE
Desafio 30 dias de CSS

### ISSUE THREAD

**Issue by Creuma-Kuzola** [MilenaCarecho/30diasDeCSS#22]
Olá Pessoal!
Sou a **Kuzola** e aceito e fazer o desafio com vocês.
Facebook: Creuma Kuzola
Linkedin : Creuma Matias
Twitter : @C_Kuzola

**Comment by MilenaCarecho** [comment]
Opa
Tudo bem ?
Comenta suas redes nesse issue [aqui](https://github.com/MilenaCarecho/30diasDeCSS/issues/1) para que as outras pessoas do projeto possa te seguir e você seguir elas 😊
