### ISSUE TITLE
Olá!

### ISSUE THREAD

**Issue by raquelrsm** [MilenaCarecho/30diasDeCSS#24]
Olá, gente! Meu nome é Raquel e espero realizar esse desafio com vocês! :grinning: :purple_heart:

- GitHub: [@raquelrsm](https://github.com/raquelrsm)
- LinkedIn: [raquelrsm](https://www.linkedin.com/in/raquelrsm/)

**Comment by MilenaCarecho** [comment]
Opa
Tudo bem ?
Comenta suas redes nesse issue [aqui](https://github.com/MilenaCarecho/30diasDeCSS/issues/1) para que as outras pessoas do projeto possa te seguir e você seguir elas 😊
