### ISSUE TITLE
Aceito :D

### ISSUE THREAD

**Issue by carolrosatto** [MilenaCarecho/30diasDeCSS#25]
Aceito o desafio! 

Carol Rosatto
Seu perfil no GitHub: carolrosatto
Seu perfil no LinkedIn: Maria Carolina Rosatto

**Comment by MilenaCarecho** [comment]
Opa
Tudo bem ?
Comenta suas redes nesse issue [aqui](https://github.com/MilenaCarecho/30diasDeCSS/issues/1) para que as outras pessoas do projeto possa te seguir e você seguir elas 😊
