### ISSUE TITLE
Opaa!!

### ISSUE THREAD

**Issue by iesusdeveloper** [MilenaCarecho/30diasDeCSS#28]
Iesus
Seu perfil no GitHub: iesusdeveloper
Seu perfil no LinkedIn: https://www.linkedin.com/in/iesus-magdiel-4184ab127/

**Comment by MilenaCarecho** [comment]
Opa
Tudo bem ?
Comenta suas redes nesse issue [aqui](https://github.com/MilenaCarecho/30diasDeCSS/issues/1) para que as outras pessoas do projeto possa te seguir e você seguir elas 😊
