### ISSUE TITLE
Desafio 30 dias de Css

### ISSUE THREAD

**Issue by tiagoridev** [MilenaCarecho/30diasDeCSS#30]
Olá, me chamo Tiago e fiquei muito animado para participar do desafio 30 dias de CSS, 

:fast_forward: Meu perfil no GitHub: [TiagoRidev](https://github.com/TiagoRidev)
:fast_forward: Seu perfil no LinkedIn: [TiagoRibeiroRj](https://www.linkedin.com/in/tiagoribeirorj/)

**_Vamos codar!_** :computer:

**Comment by TiagoRidev** [comment]
> Olá, me chamo Tiago e fiquei muito animado para participar do desafio 30 dias de CSS,
> 
> ⏩ Meu perfil no GitHub: [TiagoRidev](https://github.com/TiagoRidev)
> ⏩ Seu perfil no LinkedIn: [TiagoRibeiroRj](https://www.linkedin.com/in/tiagoribeirorj/)
> 
> **_Vamos codar!_** 💻
