### ISSUE TITLE
#30diasDeCSS

### ISSUE THREAD

**Issue by jailtonmendes** [MilenaCarecho/30diasDeCSS#31]
Olá,
Me chamo Jailton,
Sou Analista de Sistema.
Em constante estudo e apaixonado pelo Front-End.

Linkedin: https://www.linkedin.com/in/jailton-mendes/
GitHub: https://github.com/jailtonmendes

**Comment by MilenaCarecho** [comment]
Opa
Tudo bem ?
Comenta suas redes nesse issue [aqui](https://github.com/MilenaCarecho/30diasDeCSS/issues/1) para que as outras pessoas do projeto possa te seguir e você seguir elas 😊
