### ISSUE TITLE
Desafio 30 dias css

### ISSUE THREAD

**Issue by luis-marques11** [MilenaCarecho/30diasDeCSS#32]
Comente aqui com:
Seu nome: Luis Henrique
Seu perfil no GitHub: luis-marques11
Seu perfil no Twitter:
Seu perfil no LinkedIn: https://www.linkedin.com/in/luis-henrique-marques-5117473a/

**Comment by MilenaCarecho** [comment]
Opa
Tudo bem ?
Comenta suas redes nesse issue [aqui](https://github.com/MilenaCarecho/30diasDeCSS/issues/1) para que as outras pessoas do projeto possa te seguir e você seguir elas 😊
