### ISSUE TITLE
Desafio aceito!

### ISSUE THREAD

**Issue by caiobukvar** [MilenaCarecho/30diasDeCSS#33]
Nome: Caio Bukvar
Linkedin: https://www.linkedin.com/in/caiobukvar/
github:  https://github.com/BorbaBR

**Comment by MilenaCarecho** [comment]
Opa
Tudo bem ?
Comenta suas redes nesse issue [aqui](https://github.com/MilenaCarecho/30diasDeCSS/issues/1) para que as outras pessoas do projeto possa te seguir e você seguir elas 😊
