### ISSUE TITLE
Eae Povo o/

### ISSUE THREAD

**Issue by LucasAlvesGit** [MilenaCarecho/30diasDeCSS#35]
Eae povo, me chamo Lucas Alves, 
quero encarar esse desafio junto com vocês :)
GitHub: [/LucasAlvesGit](https://github.com/LucasAlvesGit)
Twitter:  [@oLucasDev](https://twitter.com/oLucasDev)
LinkedIn: [/in/LucasDeveloper](https://www.linkedin.com/in/lucasdeveloper/)

**Comment by MilenaCarecho** [comment]
Opa
Tudo bem ?
Comenta suas redes nesse issue [aqui](https://github.com/MilenaCarecho/30diasDeCSS/issues/1) para que as outras pessoas do projeto possa te seguir e você seguir elas 😊
