### ISSUE TITLE
opaaa, me chamo Romulo!!!

### ISSUE THREAD

**Issue by romulosous** [MilenaCarecho/30diasDeCSS#39]
GitHub: [@romulosous](https://github.com/romulosous)
Instagram: [@romimcarvalho](https://www.instagram.com/romimcarvalho)
LinkedIn: [@romulosous](https://www.linkedin.com/in/romulosous/)

_Originally posted by @ThamirysAbilio in https://github.com/MilenaCarecho/30diasDeCSS/issues/1#issuecomment-657726551_

**Comment by romulosous** [comment]
.

**Comment by MilenaCarecho** [comment]
Opa
Tudo bem ?
Comenta suas redes nesse issue [aqui](https://github.com/MilenaCarecho/30diasDeCSS/issues/1) para que as outras pessoas do projeto possa te seguir e você seguir elas 😊
