### ISSUE TITLE
Desafio 30 dias CSS

### ISSUE THREAD

**Issue by mialq** [MilenaCarecho/30diasDeCSS#4]
Olá meu nome é Michele Alves,

meu perfil no github: https://github.com/mialq
meu twtter: https://twitter.com/AlvesPotenza
LinkedIn: https://www.linkedin.com/in/michelequeiroz/

Estou com dúvidas sobre o projeto e o que eu devo subir aqui para o Git hub.
Muito obrigada por sua iniciativa.

**Comment by MilenaCarecho** [comment]
Opa, Michele
Tudo bem ? 
o projeto vai começar dia 20/07 (segunda feita agora 😍), eu vou postar um gif do mini projeto funcionando com o que foi usado pra fazer ele todo dia às 00h00, lá pelas 13/14h eu vou postar um tutorial de como faze-lo pelo medium para quem não conseguir realizar ou quiser ver a forma que eu fiz, o intuito é que cada pessoa que estiver participando mude alguma coisinha e poste no linkedIn/Twitter o que alterou com a #30DiasCSS :) 
Caso você tenha alguma duvida, pode me chamar no [twitter](https://twitter.com/MilenaCarecho) ou [linkedIn](https://www.linkedin.com/in/milenacarecho/) 

Comenta suas redes nesse issue [aqui](https://github.com/MilenaCarecho/30diasDeCSS/issues/1) para que as outras meninas do projeto possa te seguir e você seguir elas
