### ISSUE TITLE
Desafio aceito !

### ISSUE THREAD

**Issue by matheusgrodrigues** [MilenaCarecho/30diasDeCSS#40]
Olá pessoal, desafio aceito !

Quem quiser acompanhar o meu progresso e dar uma olhada no meu código, me acompanhe nas redes sociais abaixo. 

GitHub: https://github.com/MatheusGomesWeb
Twitter: https://twitter.com/MatheusGomesWeb
LinkedIn: https://www.linkedin.com/in/matheusgomes/

Bom desafio a todos !

**Comment by MilenaCarecho** [comment]
Opa
Tudo bem ?
Comenta suas redes nesse issue [aqui](https://github.com/MilenaCarecho/30diasDeCSS/issues/1) para que as outras pessoas do projeto possa te seguir e você seguir elas 😊
